name: Publish to PyPI

on:
  release:
    types: [published]

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
          cache: "pip"
          cache-dependency-path: "**/pyproject.toml"

      - name: ⬇️ Install build dependencies
        run: |
          python -m pip install flit

      - name: 🏗️ Build
        run: python -m flit build

      - uses: actions/upload-artifact@v4
        with:
          path: ./dist
          name: dist

  # https://docs.pypi.org/trusted-publishers/using-a-publisher/
  pypi-publish:
    needs: build
    environment: "publish"

    name: ⬆️ Upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      # Mandatory for trusted publishing
      id-token: write
    steps:
      - uses: actions/download-artifact@v6
        with:
          name: dist
          path: ./dist

      - name: 🚀 Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: ./dist
          print-hash: true
